services:
  ryu-controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw3-ryu-controller
    restart: unless-stopped
    ports:
      - "6653:6653"   # OpenFlow controller port
    volumes:
      - ./hw3_controller_ryu.py:/app/hw3_controller_ryu.py:ro
  ryu-default-controller:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ryu-default-controller
    restart: unless-stopped
    ports:
      - "6650:6653"   # Using 6650 on host to avoid conflict with the custom controller container
    command:
      - ryu-manager
      - --ofp-tcp-listen-port
      - "6653"
      - ryu.app.simple_switch_13